### ISSUE TITLE
Chrome plugin on Edge browser

### ISSUE THREAD

**Issue by nadler369** [ajyey/masked-email-manager#26]
**Describe the bug**
I set up the plugin as described, created the token with account access for masked emails and added token to plugin.
Plugin accepted token but displays no masked emails. I have dozens on my account.
I have logged out and re-entered the token to the same result.

Running Edge browser (up to date) Version 114.0.1823.67 (Official build) (64-bit) on Windows 11.
Potential plugin conflicts: Privacy Badger and uBlock Origin

**Screenshots**
![image](https://github.com/ajyey/masked-email-manager/assets/138711053/5a581179-7a92-4dcb-a9a0-5762865bde72)

**Comment by ajyey** [comment]
Hmm interesting. 

Full disclosure I have not tested the extension in Edge. I'll see if I can reproduce it and report back. 

In the meantime, can you see if you notice the same behavior using Chrome?

**Comment by ajyey** [comment]
@nadler369 I was able to reproduce this in Edge and Chrome and just pushed up a fix. Pending review in the Chrome webstore now. Will likely be reviewed and updated tomorrow. Thanks for reporting this!

**Comment by nadler369** [comment]
Fantastic. There's three possible levels of integration: Email, Email Submission, Masked Email. Which need to be selected? I actually made a separate key for just Masked Email, Masked Email and Email, and all three just to test thoroughly, but knowing exactly what the plugin needs would be helpful for knowing I'm doing it correctly.
Also, Read Only should be turned off, correct?

**Comment by ajyey** [comment]
> Fantastic. There's three possible levels of integration: Email, Email Submission, Masked Email. Which need to be selected? I actually made a separate key for just Masked Email, Masked Email and Email, and all three just to test thoroughly, but knowing exactly what the plugin needs would be helpful for knowing I'm doing it correctly. Also, Read Only should be turned off, correct?

You only need the **Masked Email** scope. And yes that's correct **Read Only** should be turned off. See my screenshot below. I'll also add a section to the README to make this more clear. 

<img width="930" alt="image" src="https://github.com/ajyey/masked-email-manager/assets/16251412/eecc6425-dd7c-407b-af0f-7460d7f924f8">

**Comment by ajyey** [comment]
@nadler369 The fix should now be live. Can you update your extension and confirm its now working on your end when you get some time?

**Comment by nadler369** [comment]
It is working and I've left a 5* review.

**Comment by ajyey** [comment]
@nadler369 thank you so much ! If anything else pops up please create another bug report and I'll do my best to push out a fix
